### ISSUE TITLE
ability to delete participant data at server from the admin panel

### ISSUE THREAD

**Issue by kanisan** [kylemcdonald/sakoku-explorer#20]
I want the ability to delete participant data at server from the admin panel after workshop.

**Comment by kylemcdonald** [comment]
i would like to solve this using the google cloud console, so the deletion is verified. i have added you to the google cloud console and i can walk you through the process.

<img width="275" alt="Screen Shot 2020-12-10 at 2 56 50 PM" src="https://user-images.githubusercontent.com/157106/101840058-49d61780-3af8-11eb-839c-637daca59030.png">
<img width="446" alt="Screen Shot 2020-12-10 at 2 57 01 PM" src="https://user-images.githubusercontent.com/157106/101840071-4d699e80-3af8-11eb-93c6-b1beff1a4092.png">
<img width="548" alt="Screen Shot 2020-12-10 at 2 57 12 PM" src="https://user-images.githubusercontent.com/157106/101840081-4f336200-3af8-11eb-913e-114953e1afbf.png">
