### ISSUE TITLE
Some data on the calendar tab is hidden behind tags and not displayed

### ISSUE THREAD

**Issue by kanisan** [kylemcdonald/sakoku-explorer#29]
<img width="1792" alt="スクリーンショット 2020-12-16 11 50 22" src="https://user-images.githubusercontent.com/1098615/102305708-066e2400-3fa4-11eb-9631-ae4975b80d2e.png">

**Comment by kylemcdonald** [comment]
this depends on the browser size. if you make the browser more narrow, then it is not a problem. there is a quick fix, which is changing the aspect ratio of the calendar. i will look into a better fix. here is what the narrow browser looks like:

<img width="1610" alt="Screen Shot 2020-12-17 at 12 08 54 PM" src="https://user-images.githubusercontent.com/157106/102538154-cc168c80-4060-11eb-8d8f-6d2e0fc562b7.png">
