### ISSUE TITLE
I want to completely block access to / games. 

### ISSUE THREAD

**Issue by kanisan** [kylemcdonald/sakoku-explorer#39]
Due to the terms & condition of use, I want to prevent the ”/games” from working completely.
Currently ”/games” is hidden and can be inferred from the source, so I would also like to remove ”/games” routing as well.

I hope we can fix it in February 2021.

**Comment by kylemcdonald** [comment]
I have fixed this in "master" branch. Now the "workshop" branch contains the status from the workshop. Please let me know if you need help building, or I can build for you 👌
